Error when `find-llvm-config` is unsuccessful

diff --git a/src/llvm/ext/find-llvm-config b/src/llvm/ext/find-llvm-config
--- a/src/llvm/ext/find-llvm-config
+++ b/src/llvm/ext/find-llvm-config
@@ -14,4 +14,10 @@ if ! LLVM_CONFIG=$(command -v "$LLVM_CONFIG"); then
     [ "$LLVM_CONFIG" ] && break
   done
 fi
-printf "$LLVM_CONFIG"
+
+if [ "$LLVM_CONFIG" ]; then
+  printf "$LLVM_CONFIG"
+else
+  printf "Error: Could not find location of llvm-config. Please specify path in environment variable LLVM_CONFIG.\n" >&2
+  exit 1
+fi
